baseURL: /
publishDir: docs
timeZone: Asia/Taipei

# sitemap
sitemap:
  changefreq: weekly # always, hourly, daily, weekly, monthly, yearly, never
  filename: sitemap.xml
  priority: 1.0

# 要用 GA，請解開以下註解，並填寫 GA Id
# googleAnalytics:

title: 網站名稱

# 導覽列
menu:
  main:
  - name: 首頁
    title: 這邊會是 a tag 的 title
    url: /
    weight: 1
  - name: 文章列表
    title: 這邊會是 a tag 的 title
    url: /posts/
    weight: 2

# Open Graph，請改成自己的網站
params:
  title: Let's Write
  description: Let's Write 製作的 Hugo init 檔案

# copyright
copyright: Let's Write. All Rights Reserved.

# 引言的長度
summaryLength: 15

# 客製參數
params:
  mainColor: "#42A6F7"
  favicon: 這邊填寫 favicon 的圖檔路徑

